NAME = T3DRECOV
DESCRIPTION = "True3D2 backup journal inspector"
COMPRESSED = NO
ARCHIVED = YES
OPTIMIZE = -Os
CFLAGS = -Wall -Wextra -Wshadow -Wconversion $(OPTIMIZE)
LTO = YES
PREFER_OS_CRT = YES
PREFER_OS_LIBC = YES

include $(shell cedev-config --makefile)
