#!/usr/bin/env python3
"""Local all-in-one level editor and CEdev build service."""

from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import threading
import webbrowser
import zipfile
from http import HTTPStatus
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any


EDITOR_DIR = Path(__file__).resolve().parent
ROOT = EDITOR_DIR.parent
BUILD_DIR = EDITOR_DIR / "build"
PORTAL_SOURCE = ROOT / "src" / "generated_levels.c"
T3D3_SOURCE = ROOT / "t3d3" / "src" / "generated_levels.c"
MAX_LEVELS = 16


class ProjectError(ValueError):
    pass


def _name(value: Any, fallback: str) -> str:
    text = str(value or fallback).strip()[:31]
    return text or fallback


def _c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _number(value: Any, label: str) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError) as error:
        raise ProjectError(f"{label} must be numeric") from error
    if not math.isfinite(result):
        raise ProjectError(f"{label} must be finite")
    return result


def _integer(value: Any, label: str, minimum: int, maximum: int) -> int:
    number = _number(value, label)
    if number != int(number) or not minimum <= int(number) <= maximum:
        raise ProjectError(f"{label} must be an integer from {minimum} to {maximum}")
    return int(number)


def _q8(value: Any, label: str, signed: bool = True) -> int:
    number = _number(value, label)
    minimum, maximum = (-128.0, 127.99609375) if signed else (0.0, 255.99609375)
    if not minimum <= number <= maximum:
        raise ProjectError(f"{label} is outside the Q8.8 range")
    return round(number * 256)


def _levels(project: dict[str, Any], engine: str) -> list[dict[str, Any]]:
    section = project.get(engine)
    if not isinstance(section, dict) or not isinstance(section.get("levels"), list):
        raise ProjectError(f"project is missing {engine}.levels")
    levels = section["levels"]
    if not 1 <= len(levels) <= MAX_LEVELS:
        raise ProjectError(f"{engine} needs 1 to {MAX_LEVELS} levels")
    if not all(isinstance(level, dict) for level in levels):
        raise ProjectError(f"every {engine} level must be an object")
    return levels


def generate_portal3d(project: dict[str, Any]) -> str:
    levels = _levels(project, "portal3d")
    output = [
        "/* Generated by editor/server.py. Do not edit by hand. */",
        '#include "game.h"',
        "",
    ]
    definitions: list[str] = []
    for level_index, level in enumerate(levels):
        label = f"Portal3D level {level_index + 1}"
        rows = level.get("cells")
        if not isinstance(rows, list) or len(rows) != 15 or any(
            not isinstance(row, list) or len(row) != 15 for row in rows
        ):
            raise ProjectError(f"{label} must contain a 15 by 15 cell grid")
        cells = [[1 if bool(cell) else 0 for cell in row] for row in rows]
        if any(cells[0][x] != 1 or cells[14][x] != 1 for x in range(15)) or any(
            cells[y][0] != 1 or cells[y][14] != 1 for y in range(15)
        ):
            raise ProjectError(f"{label} must have a solid outer wall")
        spawn = level.get("spawn")
        if not isinstance(spawn, dict):
            raise ProjectError(f"{label} is missing its spawn")
        spawn_x = _number(spawn.get("x"), f"{label} spawn X")
        spawn_y = _number(spawn.get("y"), f"{label} spawn Y")
        spawn_cell_x, spawn_cell_y = math.floor(spawn_x), math.floor(spawn_y)
        if not (0 <= spawn_cell_x < 15 and 0 <= spawn_cell_y < 15) or cells[spawn_cell_y][spawn_cell_x]:
            raise ProjectError(f"{label} spawn must be in an empty cell")
        spawn_angle = _number(spawn.get("angle", 0), f"{label} spawn angle") % 360.0

        portals = level.get("portals", [])
        if not isinstance(portals, list) or len(portals) > 10:
            raise ProjectError(f"{label} supports at most 10 directed portal links")
        tile_values = [0] * 256
        portal_values: list[tuple[int, int, int, int, int, int]] = []
        used_tiles: set[tuple[int, int]] = set()
        for portal_index, portal in enumerate(portals):
            if not isinstance(portal, dict):
                raise ProjectError(f"{label} portal {portal_index + 1} is invalid")
            values = (
                _integer(portal.get("x"), "portal X", 0, 14),
                _integer(portal.get("y"), "portal Y", 0, 14),
                _integer(portal.get("direction"), "portal direction", 0, 3),
                _integer(portal.get("targetX"), "portal target X", 0, 14),
                _integer(portal.get("targetY"), "portal target Y", 0, 14),
                _integer(portal.get("targetDirection"), "portal target direction", 0, 3),
            )
            x, y, _, target_x, target_y, _ = values
            if not cells[y][x] or not cells[target_y][target_x]:
                raise ProjectError(f"{label} portal {portal_index + 1} endpoints must be wall cells")
            if (x, y) in used_tiles:
                raise ProjectError(f"{label} has more than one portal on wall cell {x},{y}")
            used_tiles.add((x, y))
            tile_values[y * 16 + x] = portal_index + 1
            portal_values.append(values)

        padded = []
        for row in cells:
            padded.extend(row + [1])
        padded.extend([1] * 16)
        output.append(f"static const uint8_t level_{level_index}_walls[16 * 16] = {{")
        for row in range(16):
            output.append("    " + ",".join(map(str, padded[row * 16:(row + 1) * 16])) + ",")
        output.extend(["};", ""])
        output.append(f"static const uint8_t level_{level_index}_portal_tiles[16 * 16] = {{")
        entries = [f"[{index}]={value}" for index, value in enumerate(tile_values) if value]
        output.append("    " + (", ".join(entries) if entries else "0"))
        output.extend(["};", ""])
        capacity = max(1, len(portal_values))
        output.append(f"static const PortalLink level_{level_index}_portals[{capacity}] = {{")
        output.append("    " + (", ".join("{%s}" % ",".join(map(str, item)) for item in portal_values) if portal_values else "{0}"))
        output.extend(["};", ""])
        angle = (round(spawn_angle * 256.0 / 360.0) & 255) << 8
        definitions.append(
            "    {%s, level_%d_walls, level_%d_portal_tiles, level_%d_portals, %d, %d, %d, %d}"
            % (_c_string(_name(level.get("name"), f"Level {level_index + 1}")), level_index,
               level_index, level_index, _q8(spawn_x, "spawn X", signed=False),
               _q8(spawn_y, "spawn Y", signed=False), angle, len(portal_values))
        )
    output.extend([
        "const Portal3DLevelDefinition portal3d_levels[] = {",
        ",\n".join(definitions),
        "};",
        "",
        "const uint8_t portal3d_level_count =",
        "    (uint8_t)(sizeof(portal3d_levels) / sizeof(portal3d_levels[0]));",
        "",
    ])
    return "\n".join(output)


def generate_t3d3(project: dict[str, Any]) -> str:
    levels = _levels(project, "t3d3")
    output = [
        "/* Generated by editor/server.py. Do not edit by hand. */",
        '#include "level.h"',
        "",
    ]
    catalog: list[str] = []
    for level_index, level in enumerate(levels):
        label = f"T3D3 level {level_index + 1}"
        rooms = level.get("rooms")
        if not isinstance(rooms, list) or not 1 <= len(rooms) <= 8:
            raise ProjectError(f"{label} needs 1 to 8 rooms")
        spawn = level.get("spawn")
        portals = level.get("portals")
        if not isinstance(spawn, dict) or not isinstance(portals, list) or len(portals) != 2:
            raise ProjectError(f"{label} needs a spawn and two portal records")
        room_records: list[str] = []
        parsed_rooms: list[tuple[int, int, int, int, int, int]] = []
        for room_index, room in enumerate(rooms):
            if not isinstance(room, dict):
                raise ProjectError(f"{label} room {room_index + 1} is invalid")
            values = tuple(_q8(room.get(key), f"room {room_index + 1} {key}") for key in
                           ("minX", "maxX", "minY", "maxY", "minZ", "maxZ"))
            if values[1] - values[0] < 512 or values[3] - values[2] < 512 or values[5] - values[4] < 512:
                raise ProjectError(f"{label} room {room_index + 1} must be at least 2 units on every axis")
            colors = room.get("colors")
            if not isinstance(colors, list) or len(colors) != 6:
                raise ProjectError(f"{label} room {room_index + 1} needs six colors")
            color_values = [_integer(color, "face color", 0, 12) for color in colors]
            parsed_rooms.append(values)
            room_records.append("        {%s,{%s}}" % (",".join(map(str, values)), ",".join(map(str, color_values))))
        spawn_room = _integer(spawn.get("room"), "spawn room", 0, len(rooms) - 1)
        spawn_values = tuple(_q8(spawn.get(axis), f"spawn {axis}") for axis in ("x", "y", "z"))
        bounds = parsed_rooms[spawn_room]
        if not (bounds[0] < spawn_values[0] < bounds[1] and bounds[2] < spawn_values[1] < bounds[3]
                and bounds[4] + 64 <= spawn_values[2] < bounds[5]):
            raise ProjectError(f"{label} spawn must be inside its room")
        portal_records: list[str] = []
        active_mask = 0
        for portal_index, portal in enumerate(portals):
            if not isinstance(portal, dict):
                raise ProjectError(f"{label} portal {portal_index + 1} is invalid")
            active = bool(portal.get("active"))
            room_index = _integer(portal.get("room", 0), "portal room", 0, len(rooms) - 1)
            face = _integer(portal.get("face", 0), "portal face", 0, 5)
            position = [_q8(portal.get(axis, 0), f"portal {axis}") for axis in ("x", "y", "z")]
            if active:
                active_mask |= 1 << portal_index
                bounds = parsed_rooms[room_index]
                if face <= 1:
                    valid = position[2] == bounds[4 + face] and \
                        bounds[0] + 384 <= position[0] <= bounds[1] - 384 and \
                        bounds[2] + 448 <= position[1] <= bounds[3] - 448
                elif face <= 3:
                    valid = position[1] == bounds[2 + (face - 2)] and \
                        bounds[0] + 384 <= position[0] <= bounds[1] - 384 and \
                        bounds[4] + 448 <= position[2] <= bounds[5] - 448
                else:
                    valid = position[0] == bounds[face - 4] and \
                        bounds[2] + 384 <= position[1] <= bounds[3] - 384 and \
                        bounds[4] + 448 <= position[2] <= bounds[5] - 448
                if not valid:
                    raise ProjectError(
                        f"{label} portal {portal_index + 1} must be on its selected face "
                        "with room for the full aperture"
                    )
            portal_records.append("{%d,%d,%s}" % (room_index, face, ",".join(map(str, position))))
        output.extend([
            "typedef struct __attribute__((packed)) {",
            "    True3DLevelHeader header;",
            f"    True3DRoomRecord rooms[{len(rooms)}];",
            f"}} GeneratedT3D3Level{level_index};",
            "",
            f"static const GeneratedT3D3Level{level_index} generated_level_{level_index} = {{",
            "    {{'T','3','D','1'}, TRUE3D_LEVEL_VERSION, %d, %d, %d, %s, {%s}}," %
            (len(rooms), spawn_room, active_mask, ",".join(map(str, spawn_values)), ",".join(portal_records)),
            "    {",
            ",\n".join(room_records),
            "    }",
            "};",
            "",
        ])
        catalog.append("    {%s, &generated_level_%d, sizeof(generated_level_%d)}" %
                       (_c_string(_name(level.get("name"), f"Level {level_index + 1}")), level_index, level_index))
    output.extend([
        "const T3D3EmbeddedLevel t3d3_embedded_levels[] = {",
        ",\n".join(catalog),
        "};",
        "",
        "const uint8_t t3d3_embedded_level_count =",
        "    (uint8_t)(sizeof(t3d3_embedded_levels) / sizeof(t3d3_embedded_levels[0]));",
        "",
    ])
    return "\n".join(output)


def write_generated(project: dict[str, Any], engines: list[str]) -> list[Path]:
    written = []
    for engine in engines:
        if engine not in ("portal3d", "t3d3"):
            raise ProjectError("build target must be portal3d, t3d3, or both")
        path = PORTAL_SOURCE if engine == "portal3d" else T3D3_SOURCE
        content = generate_portal3d(project) if engine == "portal3d" else generate_t3d3(project)
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_text(content, encoding="utf-8", newline="\n")
        os.replace(temporary, path)
        written.append(path)
    return written


def _run_make(directory: Path) -> str:
    process = subprocess.run(
        ["make", "-B"], cwd=directory, text=True, stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT, timeout=180, check=False,
    )
    if process.returncode:
        raise RuntimeError(f"Build failed in {directory.name}:\n{process.stdout}")
    return process.stdout


def build_project(project: dict[str, Any], target: str) -> tuple[Path, str]:
    engines = ["portal3d", "t3d3"] if target == "both" else [target]
    if any(engine not in ("portal3d", "t3d3") for engine in engines):
        raise ProjectError("build target must be portal3d, t3d3, or both")
    write_generated(project, engines)
    logs = []
    binaries: list[tuple[Path, str]] = []
    if "portal3d" in engines:
        logs.append(_run_make(ROOT))
        binaries.append((ROOT / "bin" / "PORTAL3D.8xp", "Portal3D/PORTAL3D.8xp"))
    if "t3d3" in engines:
        logs.append(_run_make(ROOT / "t3d3"))
        binaries.append((ROOT / "t3d3" / "bin" / "T3D3DEV.8xp", "T3D3/T3D3DEV.8xp"))
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    package = BUILD_DIR / f"PortalR3D-{target}-package.zip"
    with zipfile.ZipFile(package, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for source, destination in binaries:
            archive.write(source, destination)
        archive.writestr(
            "README.txt",
            "PortalR 3D editor package\n\nThe level selector and all authored levels are embedded in each .8xp.\n"
            "Transfer the desired program to a TI-84 Plus CE and launch it.\n",
        )
        archive.writestr("project.json", json.dumps(project, indent=2))
    return package, "\n".join(logs)


class EditorHandler(SimpleHTTPRequestHandler):
    server_version = "PortalR3DEditor/1.0"

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, directory=str(EDITOR_DIR), **kwargs)

    def _json(self, status: int, value: dict[str, Any]) -> None:
        body = json.dumps(value).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self) -> None:  # noqa: N802
        if self.path not in ("/api/generate", "/api/build"):
            self._json(HTTPStatus.NOT_FOUND, {"error": "Unknown endpoint"})
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            if not 0 < length <= 2_000_000:
                raise ProjectError("request is empty or too large")
            request = json.loads(self.rfile.read(length))
            project = request.get("project")
            target = request.get("target", "both")
            if not isinstance(project, dict):
                raise ProjectError("request is missing a project")
            if self.path == "/api/generate":
                engines = ["portal3d", "t3d3"] if target == "both" else [target]
                paths = write_generated(project, engines)
                self._json(HTTPStatus.OK, {"ok": True, "files": [str(path.relative_to(ROOT)) for path in paths]})
            else:
                package, log = build_project(project, target)
                self._json(HTTPStatus.OK, {
                    "ok": True, "package": package.name,
                    "url": f"/build/{package.name}", "log": log[-12000:],
                })
        except (ProjectError, json.JSONDecodeError) as error:
            self._json(HTTPStatus.BAD_REQUEST, {"error": str(error)})
        except (OSError, RuntimeError, subprocess.TimeoutExpired) as error:
            self._json(HTTPStatus.INTERNAL_SERVER_ERROR, {"error": str(error)})

    def log_message(self, format: str, *args: Any) -> None:
        print(f"[editor] {self.address_string()} - {format % args}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--no-browser", action="store_true")
    args = parser.parse_args()
    server = ThreadingHTTPServer(("127.0.0.1", args.port), EditorHandler)
    url = f"http://127.0.0.1:{server.server_port}/"
    print(f"PortalR 3D editor: {url}")
    print("Press Ctrl+C to stop.")
    if not args.no_browser:
        threading.Timer(0.5, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
