/* Generated by editor/server.py. Do not edit by hand. */
#include "level.h"

typedef struct __attribute__((packed)) {
    True3DLevelHeader header;
    True3DRoomRecord rooms[2];
} GeneratedT3D3Level0;

static const GeneratedT3D3Level0 generated_level_0 = {
    {{'T','3','D','1'}, TRUE3D_LEVEL_VERSION, 2, 0, 3, 0,512,384, {{0,3,0,2560,640},{1,1,3072,1024,1280}}},
    {
        {-1024,1024,0,2560,0,1280,{2,3,5,4,5,5}},
        {2048,4096,0,2048,0,1280,{6,7,9,8,9,9}}
    }
};

typedef struct __attribute__((packed)) {
    True3DLevelHeader header;
    True3DRoomRecord rooms[1];
} GeneratedT3D3Level1;

static const GeneratedT3D3Level1 generated_level_1 = {
    {{'T','3','D','1'}, TRUE3D_LEVEL_VERSION, 1, 0, 0, 0,512,384, {{0,3,0,2560,640},{0,2,0,0,640}}},
    {
        {-1024,1024,0,2560,0,1280,{2,3,5,4,5,5}}
    }
};

const T3D3EmbeddedLevel t3d3_embedded_levels[] = {
    {"Wall to ceiling", &generated_level_0, sizeof(generated_level_0)},
    {"Single chamber", &generated_level_1, sizeof(generated_level_1)}
};

const uint8_t t3d3_embedded_level_count =
    (uint8_t)(sizeof(t3d3_embedded_levels) / sizeof(t3d3_embedded_levels[0]));
