/* Generated by editor/server.py. Do not edit by hand. */
#include "game.h"

const uint8_t portal3d_render_max_depth = 6;
const uint8_t portal3d_always_show_fps = 1;

static const uint8_t level_0_walls[16 * 16] = {
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,
    1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,
    1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
};

static const uint8_t level_0_portal_tiles[16 * 16] = {
    [3]=1, [5]=1, [7]=1, [32]=1, [64]=1, [94]=1, [110]=1, [149]=1, [208]=1, [213]=1
};

static const PortalLink level_0_portals[10] = {
    {0,13,1,5,13,0}, {5,13,0,0,13,1}, {0,4,1,5,9,0}, {5,9,0,0,4,1}, {5,0,3,7,0,3}, {7,0,3,5,0,3}, {14,5,0,14,6,0}, {14,6,0,14,5,0}, {0,2,1,3,0,3}, {3,0,3,0,2,1}
};

static const GameplaySpawn level_0_enemies[4] = {
    {12,12,GAME_ENEMY_BOSS}, {9,5,GAME_ENEMY_HUNTER},
    {3,12,GAME_ENEMY_HUNTER}, {12,3,GAME_ENEMY_TURRET}
};

static const GameplaySpawn level_0_pickups[4] = {
    {2,3,GAME_PICKUP_AMMO}, {7,6,GAME_PICKUP_HEALTH},
    {10,10,GAME_PICKUP_SHELLS}, {2,9,GAME_PICKUP_LIFE}
};

static const DoorSpawn level_0_doors[2] = {
    {6,7,0}, {5,11,1}
};

static const uint8_t level_1_walls[16 * 16] = {
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,
    1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,
    1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,
    1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,
    1,0,0,0,0,1,1,1,1,1,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,
    1,0,0,0,0,1,0,1,0,1,0,0,0,0,1,1,
    1,1,0,0,0,1,0,0,0,1,0,0,0,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
};

static const uint8_t level_1_portal_tiles[16 * 16] = {
    [36]=1, [42]=1, [50]=1, [60]=1, [103]=1, [112]=1, [126]=1, [135]=1, [163]=1, [167]=1, [171]=1, [192]=1, [199]=1, [206]=1
};

static const PortalLink level_1_portals[20] = {
    {4,2,1,10,2,1}, {10,2,1,4,2,1}, {2,3,2,14,12,0}, {14,12,0,2,3,2}, {12,3,2,0,12,1}, {0,12,1,12,3,2}, {11,10,2,7,12,0}, {7,12,0,11,10,2}, {3,10,2,7,12,1}, {7,12,1,3,10,2}, {0,7,1,7,8,1}, {7,8,1,0,7,1}, {14,7,0,7,8,0}, {7,8,0,14,7,0}, {7,8,2,7,6,3}, {7,6,3,7,8,2}, {7,10,2,7,8,3}, {7,8,3,7,10,2}, {10,2,0,4,2,0}, {4,2,0,10,2,0}
};

static const GameplaySpawn level_1_enemies[5] = {
    {12,12,GAME_ENEMY_BOSS}, {2,12,GAME_ENEMY_HUNTER},
    {12,5,GAME_ENEMY_HUNTER}, {2,5,GAME_ENEMY_TURRET},
    {11,8,GAME_ENEMY_TURRET}
};

static const GameplaySpawn level_1_pickups[5] = {
    {8,1,GAME_PICKUP_AMMO}, {3,8,GAME_PICKUP_HEALTH},
    {10,6,GAME_PICKUP_SHELLS}, {9,12,GAME_PICKUP_AMMO},
    {12,1,GAME_PICKUP_LIFE}
};

static const DoorSpawn level_1_doors[2] = {
    {6,3,0}, {7,9,1}
};

static const uint8_t level_2_walls[16 * 16] = {
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,
    1,1,1,0,1,1,0,0,0,1,1,0,1,1,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,
    1,1,1,0,1,1,0,0,0,1,1,0,1,1,1,1,
    1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,
    1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
};

static const uint8_t level_2_portal_tiles[16 * 16] = {0};
static const PortalLink level_2_portals[1] = {{0}};

static const GameplaySpawn level_2_enemies[7] = {
    {12,12,GAME_ENEMY_BOSS}, {11,11,GAME_ENEMY_BOSS},
    {3,3,GAME_ENEMY_HUNTER}, {11,3,GAME_ENEMY_HUNTER},
    {3,11,GAME_ENEMY_HUNTER}, {7,6,GAME_ENEMY_TURRET},
    {7,10,GAME_ENEMY_TURRET}
};

static const GameplaySpawn level_2_pickups[6] = {
    {3,6,GAME_PICKUP_AMMO}, {11,6,GAME_PICKUP_SHELLS},
    {3,8,GAME_PICKUP_HEALTH}, {11,8,GAME_PICKUP_AMMO},
    {7,12,GAME_PICKUP_HEALTH}, {7,3,GAME_PICKUP_LIFE}
};

static const DoorSpawn level_2_doors[4] = {
    {3,5,1}, {11,5,1}, {3,9,1}, {11,9,1}
};

const Portal3DLevelDefinition portal3d_levels[] = {
    {"Test chambers", level_0_walls, level_0_portal_tiles, level_0_portals,
        384, 640, 2048, 10, level_0_enemies, level_0_pickups, level_0_doors,
        4, 4, 2, 13, 12},
    {"Maze lockdown", level_1_walls, level_1_portal_tiles, level_1_portals,
        1920, 384, 4096, 20, level_1_enemies, level_1_pickups, level_1_doors,
        5, 5, 2, 13, 12},
    {"Core overload", level_2_walls, level_2_portal_tiles, level_2_portals,
        384, 384, 0, 0, level_2_enemies, level_2_pickups, level_2_doors,
        7, 6, 4, 13, 13}
};

const uint8_t portal3d_level_count =
    (uint8_t)(sizeof(portal3d_levels) / sizeof(portal3d_levels[0]));
